"""One-off (well, re-runnable) tool: reads the current demo database and
writes scripts/demo_seed_data.py, a frozen, hardcoded snapshot of every
row in it. That generated file -- not this one -- is what app.py loads
on startup when the demo database is empty (see load_demo_seed_if_empty
in app.py). Re-run this only if you deliberately want to refresh the
demo dataset to a new snapshot (e.g. after regenerating with
generate_synthetic_data.py and manually tweaking something); everyday
startup never touches this script.

Usage:
    python scripts/export_demo_seed.py
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import db

# FK-safe order: ambassadors and members reference each other (members
# has ambassador_id, ambassadors has member_id), so both are loaded with
# foreign key checks off (see load_into() in the generated file) rather
# than needing a two-phase insert/update dance here.
TABLES = [
    "events", "members", "ambassadors", "attendance",
    "feedback", "ambassador_social_posts", "deletion_log",
]

OUTPUT_PATH = Path(__file__).parent / "demo_seed_data.py"


def main():
    conn = db.get_connection()
    table_blocks = []
    for table in TABLES:
        cur = conn.execute(f"SELECT * FROM {table}")
        columns = [d[0] for d in cur.description]
        rows = [tuple(row) for row in cur.fetchall()]
        table_blocks.append((table, columns, rows))

    lines = [
        '"""Frozen snapshot of the demo dataset -- generated by',
        "scripts/export_demo_seed.py, not written by hand. Loaded by",
        "load_demo_seed_if_empty() in app.py on startup whenever the demo",
        "database is empty, so every fresh checkout or Streamlit Cloud",
        "deploy of this branch shows the exact same ~5 events, ~30 members,",
        "~8 ambassadors, feedback, and social posts -- not freshly",
        'randomized data each time."""',
        "",
        "DEMO_SEED = {",
    ]
    for table, columns, rows in table_blocks:
        lines.append(f"    {table!r}: {{")
        lines.append(f"        'columns': {tuple(columns)!r},")
        lines.append("        'rows': [")
        for row in rows:
            lines.append(f"            {row!r},")
        lines.append("        ],")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append("def load_into(conn) -> None:")
    lines.append('    """Insert every row above into an already-schema-initialized,')
    lines.append("    empty connection. Foreign keys off for the duration of the load")
    lines.append("    -- members and ambassadors reference each other, and this frozen")
    lines.append("    snapshot's row order isn't guaranteed to satisfy that cycle")
    lines.append('    incrementally, only once every row is in."""')
    lines.append("    conn.execute('PRAGMA foreign_keys = OFF')")
    lines.append(f"    for table in {TABLES!r}:")
    lines.append("        spec = DEMO_SEED[table]")
    lines.append("        placeholders = ', '.join('?' for _ in spec['columns'])")
    lines.append("        columns_sql = ', '.join(spec['columns'])")
    lines.append("        conn.executemany(")
    lines.append("            f'INSERT INTO {table} ({columns_sql}) VALUES ({placeholders})',")
    lines.append("            spec['rows'],")
    lines.append("        )")
    lines.append("    conn.commit()")
    lines.append("    conn.execute('PRAGMA foreign_keys = ON')")
    lines.append("")

    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    total_rows = sum(len(rows) for _, _, rows in table_blocks)
    print(f"Wrote {OUTPUT_PATH} -- {total_rows} rows across {len(TABLES)} tables.")


if __name__ == "__main__":
    main()
